---
abstract: 'Nephia plugin that provides automated fill-in-form feature'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Nephia-Plugin-FillInForm
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Nephia::Plugin::FillInForm:
    file: lib/Nephia/Plugin/FillInForm.pm
    version: 0.02
requires:
  HTML::FillInForm: 0
  Nephia: 0.23
  Nephia::DSLModifier: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/Nephia-Plugin-FillInForm/issues
  homepage: https://github.com/ytnobody/Nephia-Plugin-FillInForm
  repository: git://github.com/ytnobody/Nephia-Plugin-FillInForm.git
version: 0.02
x_contributors:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
